### ISSUE TITLE
Uploading firmware to STM32

### ISSUE THREAD

**Issue by wajihalam** [glegrain/STM32-SPI-Bootloader-host#3]
Thank you for providing this repo. Can this repo be used to upload firmware through SPI? If yes, how can I use it to send firmware to another STM32 microcontroller? Could you please share more details on this?

**Comment by kaushaleinfo** [comment]
> Thank you for providing this repo. Can this repo be used to upload firmware through SPI? If yes, how can I use it to send firmware to another STM32 microcontroller? Could you please share more details on this?

then convert bin or hex to hex array and send byte by byte using loop and write into flash simple as that
